### ISSUE TITLE
Import issue in plot_calibration notebook

### ISSUE THREAD

**Issue by Alexis-IMBERT** [ambroiseodt/tsim#1]
Hi ! 
I tried to lauch your code, 
I got an issue with these import : 
```python
from src.datasets.read_dataset import RealDataSet
from src.models.diverse_ensemble import DiverseEnsembleMLP
```

indeed, the only folder in src folder is tsim so we need to add tsim in the import by : 
```python
from src.tsim.datasets.read_dataset import RealDataSet
from src.tsim.models.diverse_ensemble import DiverseEnsembleMLP 
```

**Comment by ambroiseodt** [comment]
Hello, thanks for noticing, and sorry for the disturbance, the package is still under development.
As it is a package, you can simply do ```import tsim``` or ``` from tsim import <function>``` to use it.
I updated the notebooks accordingly.
